### ISSUE TITLE
Changing aperio imagescope xml format annotation to  coco json annotation 

### ISSUE THREAD

**Issue by Monk5088** [pjl54/WSI_handling#6]
Dear author,
Can you explain how to use your code for converting Aperio Imagescope annotation to Coco .json annotation?
I have an annotation file in this format:
```
Annotations MicronsPerPixel="0.500000">
	<Annotation Id="1" Name="" ReadOnly="0" NameReadOnly="0" LineColorReadOnly="0" Incremental="0" Type="4" LineColor="65280" Visible="1" Selected="1" MarkupImagePath="" MacroName="">
		<Attributes>
			<Attribute Name="Description" Id="0" Value=""/>
		</Attributes>
		<Regions>
			<RegionAttributeHeaders>
				<AttributeHeader Id="9999" Name="Region" ColumnWidth="-1"/>
				<AttributeHeader Id="9997" Name="Length" ColumnWidth="-1"/>
				<AttributeHeader Id="9996" Name="Area" ColumnWidth="-1"/>
				<AttributeHeader Id="9998" Name="Text" ColumnWidth="-1"/>
				<AttributeHeader Id="1" Name="Description" ColumnWidth="-1"/>
			</RegionAttributeHeaders>
			<Region Id="1" Type="2" Zoom="1" Selected="0" ImageLocation="" ImageFocus="0" Length="138.3" Area="1517.4" LengthMicrons="69.2" AreaMicrons="379.3" Text="Mitosis" NegativeROA="0" InputRegionId="0" Analyze="0" DisplayId="1">
				<Attributes/>
				<Vertices>
					<Vertex X="6595" Y="24009"/>
					<Vertex X="6642" Y="24051"/>
				</Vertices>
.
.
.
.
.
				</Vertices>
			</Region>
		</Regions>
		<Plots/>
	</Annotation>
</Annotations>
```
And I want to convert this annotation .XML file into Coco.json format :
```
{"info": {"description": "MItosis Domain Generalization Challenge (MIDOG) 2021 - Training set", "version": "1.0", "year": 2020, "contributor": "Marc Aubreville, Christof Bertram, Mitko Veta, Robert Klopfleisch, Nikolas Stathonikos, Natalie ter Hoeve, Taryn Donovan, Katharina Breininger, Andreas Maier", "date_created": "2021/04/01"}, "licenses": [{"url": "http://creativecommons.org/licenses/by-nc-nd/2.0/", "id": 1, "name": "Attribution-NonCommercial-NoDerivs License"}], "images": [{"license": 1, "file_name": "001.tiff", "id": 1, "width": 7215, "height": 5412}, {"license": 1, "file_name": "002.tiff", "id": 2, "width": 7215, "height": 5412}, {"license": 1, "file_name": "003.tiff", "id": 3, "width": 7215, "height": 5412},......
 "categories": [{"id": 1, "name": "mitotic figure"}, {"id": 2, "name": "not mitotic figure"}], "annotations": [{"bbox": [4336, 346, 4386, 396], "category_id": 2, "image_id": 1, "id": 1}, {"bbox": [756, 872, 806, 922], "category_id": 2, "image_id": 1, "id": 2}, {"bbox": [270, 4044, 320, 4094], "category_id": 2, "image_id": 1, "id": 3}, {"bbox": [6672.5, 706.5, 6722.5, 756.5], "category_id": 2, "image_id": 1, "id": 4}, {"bbox": [1872, 319, 1922, 369], "category_id": 2, "image_id": 2, "id": 5}, {"bbox": [4397, 191, 4447, 241], "category_id": 1, "image_id": 2, "id": 6}, 
...........
"category_id": 2, "image_id": 150, "id": 4434}, {"bbox": [2681.5, 2846, 2731.5, 2896], "category_id": 2, "image_id": 150, "id": 4435}]}
```
Can you please help me with how to perform the following conversion?
Thanking you in advance,
Warm regards,
Harshit

**Comment by Monk5088** [comment]
Another same  link but uploaded in github:
https://github.com/JiweiMaster/imagescope_xml_utils

**Comment by pjl54** [comment]
There are many ways to do this, my suggestion is to parse the XML file with the python XML library, for example in https://github.com/pjl54/WSI_handling/blob/master/WSI_handling/annotation_handlers.py#L61

Using that object, you can iterate through the fields of the XML by name, in the ImageScope XML format you probably want to iterate through [annotations](https://github.com/pjl54/WSI_handling/blob/master/WSI_handling/annotation_handlers.py#L69). From each annotation, you build up a dictionary with field names corresponding to the names in the COCO format. 

Once you have your dictionary with the appropriate field names and values, you can use [the python json library](https://docs.python.org/3/library/json.html) to dump the dictionary to a json file. 

I haven't used the COCO format for storing annotations so I'm not sure exactly what ImageScope XML field name corresponds to which COCO field name, but looking at your example XML file, you have two vertices, which could be defining a line, and in the COCO example, you have what I assume to be two coordinates, but they're in a field called "bbox", perhaps they're corners of a bounding box?

It also looks like your COCO file has an "image_id" field, are annotations of multiple images being defined in a single file? ImageScope outputs one file per image, so there will be a difference there.

**Comment by Monk5088** [comment]
Hey can you share the code to perform this conversion, it would be really great if you could send just a working
[xml files.zip](https://github.com/pjl54/WSI_handling/files/9284395/xml.files.zip)
 implementation of this conversion I can share the XML file with you , if it works on it then I can try working on it.
Thanking you in advance,
Warm regards,
Harshit

**Comment by Monk5088** [comment]
You can use the XML file and see if it shows any conversion like that of coco format

**Comment by Monk5088** [comment]
> There are many ways to do this, my suggestion is to parse the XML file with the python XML library, for example in https://github.com/pjl54/WSI_handling/blob/master/WSI_handling/annotation_handlers.py#L61
> 
> Using that object, you can iterate through the fields of the XML by name, in the ImageScope XML format you probably want to iterate through [annotations](https://github.com/pjl54/WSI_handling/blob/master/WSI_handling/annotation_handlers.py#L69). From each annotation, you build up a dictionary with field names corresponding to the names in the COCO format.
> 
> Once you have your dictionary with the appropriate field names and values, you can use [the python json library](https://docs.python.org/3/library/json.html) to dump the dictionary to a json file.
> 
> I haven't used the COCO format for storing annotations so I'm not sure exactly what ImageScope XML field name corresponds to which COCO field name, but looking at your example XML file, you have two vertices, which could be defining a line, and in the COCO example, you have what I assume to be two coordinates, but they're in a field called "bbox", perhaps they're corners of a bounding box?
> 
> It also looks like your COCO file has an "image_id" field, are annotations of multiple images being defined in a single file? ImageScope outputs one file per image, so there will be a difference there.

Yes the COCO format has multiple image id as it has several .tiff files which have regions of interest for each image so it gives the bbox coordinates as well as the image id for which the annotation is present,
but in my case, the image id is the same for all the regions, i.e. I have a single .scn file and it has multiple annotations scattered across the image which are written in the XML file as ellipse box coordinates which I have figured out as the top left and bot right corner coords, ( one big .scn file and its XML file as label annotations are new input to test my already trained model)
so with this information would you know how can I implement this conversion to .json file?
Thanks for your help.

**Comment by pjl54** [comment]
> Hey can you share the code to perform this conversion

I don't have code for doing this conversion, but my recommendations could be a starting point for you.

> which are written in the XML file as ellipse box coordinates which I have figured out as the top left and bot right corner coords

It seems like you need more than two points to define an ellipse, since you also need the minor axis length or the eccentricity or something. I see in your example XML that you do have the annotation area, so I suppose you could use that along with the bounding box corner points to derive the other parameters of the ellipse. 

> so with this information would you know how can I implement this conversion to .json file?

As I said, I'm unfamiliar with the structure of the coco file you want, so all I can offer is my earlier suggestion of how to iterate through the annotations in the XML file and how to write a json file to disk. You will need to figure out how
