### ISSUE TITLE
Issue when dealing with multiple annotations

### ISSUE THREAD

**Issue by jjagtap** [pjl54/WSI_handling#7]
Hi.I have 2-3 annotation regions in my XML, all green color. I was interested to load all of them. 1.How to select all annotation automatically with function 'w.get_dimensions_of_annotation' or any other more useful function for this. 2.How to use 'w.mask_out_annotation' to get mask out at full image size when we have multiple annotations. I was expecting function to plot extract all # mask from annotation list but it fails to extract currently when there are more than 1 annotations. Thanks!

**Comment by pjl54** [comment]
Could you provide the code you're running to try to extract the annotations, starting from when you create the wsi object? And then the error you get or how you know that it failed?

get_dimensions_of_annotation returns the dimensions of a single annotation. So if you want to know the dimensions of each annotation, you'll first need to use get_points to find out how many annotations you have, then call get_dimensions_of_annotation with annotation_idx as each integer from 0 to the number of annotations.

**Comment by jjagtap** [comment]
Thanks @pjl54. Got it.  I have xml file with 2-3 cortex contours in them. so I have to load them in loop, with annotation_idx=0/1/2... <b/>
xml_fname =  'test.xml' 
fnmae='test.svs'
img = wsi(fname,xml_fname) 
img_dims = img.get_dimensions_of_annotation(colors_to_use=args.color,annotation_idx=0) <b/>

2. Also I was able to show the mask file. Not sure what was glitch but same thing was not working before.
![cortexmask](https://user-images.githubusercontent.com/65933407/221025942-c07aa5e4-da69-4711-a69a-cfddbbacd47a.png)
